INSERT INTO falha (id, descricao) VALUES ("0x00", "Sem falha");
INSERT INTO falha (id, descricao) VALUES ("0x01", "Falha sequencia de fases");
INSERT INTO falha (id, descricao) VALUES ("0x02", "Falha sobrecorrente motor eletrico");
INSERT INTO falha (id, descricao) VALUES ("0x03", "Falha sobrecorrente ventilador");
INSERT INTO falha (id, descricao) VALUES ("0x04", "Falha temperatura alta de saida do ar");
INSERT INTO falha (id, descricao) VALUES ("0x05", "Falha temperatura alta do oleo");
INSERT INTO falha (id, descricao) VALUES ("0x06", "Falha temperatura alta do ponto de orvalho");
INSERT INTO falha (id, descricao) VALUES ("0x07", "Falha sensor TS");
INSERT INTO falha (id, descricao) VALUES ("0x08", "Falha sensor TO");
INSERT INTO falha (id, descricao) VALUES ("0x09", "Falha sensor TPO");
INSERT INTO falha (id, descricao) VALUES ("0x0A", "Falha sensor Tamb");
INSERT INTO falha (id, descricao) VALUES ("0x0B", "Falha sensor P1");
INSERT INTO falha (id, descricao) VALUES ("0x0C", "N/D");
INSERT INTO falha (id, descricao) VALUES ("0x0D", "Falha sobrecorrente secador integrado");
INSERT INTO falha (id, descricao) VALUES ("0x0E", "Falha pressao alta - secador integrado");
INSERT INTO falha (id, descricao) VALUES ("0x0F", "Falha pressao baixa - secador integrado");
INSERT INTO falha (id, descricao) VALUES ("0x10", "Falha pressao baixa linha de ar comprimido");
INSERT INTO falha (id, descricao) VALUES ("0x11", "Falha pressao alta linha de ar comprimido");
