INSERT INTO alerta (id, descricao) VALUES ("0x00", "Nenhuma alerta");
INSERT INTO alerta (id, descricao) VALUES ("0x12", "Alerta 1a troca de filtro");
INSERT INTO alerta (id, descricao) VALUES ("0x13", "Alerta troca de oleo");
INSERT INTO alerta (id, descricao) VALUES ("0x14", "Alerta troca filtro oleo");
INSERT INTO alerta (id, descricao) VALUES ("0x15", "Alerta troca filtro separador");
INSERT INTO alerta (id, descricao) VALUES ("0x16", "Alerta troca filtro de ar");
INSERT INTO alerta (id, descricao) VALUES ("0x17", "Alerta troca correias");
INSERT INTO alerta (id, descricao) VALUES ("0x18", "Alerta limpeza resfriador ar/oleo");
INSERT INTO alerta (id, descricao) VALUES ("0x19", "Alerta revisao geral unidade compressora");
INSERT INTO alerta (id, descricao) VALUES ("0x1A", "Alerta elemento coalescente saturado (secador integrado)");
