version: '3.9'

services:
  mysql_db:
    image: mysql:8.0 
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456 
      MYSQL_DATABASE: compressor_db 
    ports:
      - "3307:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/MySQL/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - api

networks:
  api:
    driver: bridge

volumes:
  mysql_data: 