services:
  db:
    image: docker.io/mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: compressor_db
    ports:
      - "9306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - api

  api:
    build: .
    container_name: compressor_api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/compressor_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "9091:8080"
    networks:
      - api

networks:
  api:
    driver: bridge

volumes:
  mysql_data:
