name: Deploy Podman Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Deploy via Podman Compose
        run: |
          cd ./AirCompressorMonitor/API-Compressor
          podman-compose down
          podman-compose up -d --build
